#
# Weblate testsuite for Travis-CI
#
# - Test against all supported Django versions with sqlite
# - Test against all supported databases with current Django
# - Run Selenium tests on current Django
# - Run pylint/pep8 checker
#
language: python
# only python 2.7 is supported
python:
  - "2.7"
# build matrix configuration
env:
  matrix:
    - CI_DJANGO="Django>=1.7,<1.8" CI_LINT=1
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=mysql
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=postgresql
    - CI_DJANGO="Django>=1.7,<1.8"
    - CI_DJANGO="https://www.djangoproject.com/download/1.8a1/tarball/"
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=postgresql CI_RUN_TESTS="-p test_selenium.py" CI_SELENIUM=1
    - CI_DJANGO="https://github.com/django/django/zipball/master"
  global:
    - DJANGO_SETTINGS_MODULE=weblate.settings_test
    - CI_REQUIREMENTS=travis
matrix:
  allow_failures:
    - python: "2.7"
      env: CI_DJANGO="https://github.com/django/django/zipball/master"
# commands to install dependencies
install:
  - ./ci/install
# create databases
before_script:
  - ./ci/setup-env
# commands to run tests
script:
  - if [ -z "$CI_LINT" ] ; then ./ci/run-test ; else ./ci/run-lint ; fi
# upload coverage
after_script:
  - if [ -z "$CI_LINT" ] ; then coveralls ; fi
  - if [ -z "$CI_LINT" ] ; then ocular --data-file ".coverage" --config-file ".coveragerc" ; fi
# cache configuration
cache:
  directories:
    - $HOME/.cache/pip
# use docker based faster build
sudo: false
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
